#!/usr/bin/env bash
#
#/ command: rpm:erase: "Erases (removes) the specified package from the system"
#
#/ usage: rerun rpm:erase  --package-name <> 
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: PACKAGE_NAME

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: rpm:erase. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/erase/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/erase/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# ------------------------------
# Your implementation goes here.
# ------------------------------

if rpm --quiet -q $PACKAGE_NAME
then
  sudo rpm --erase $PACKAGE_NAME
fi

exit $?

# Done
